### ISSUE TITLE
.encode always throws 'int' is not a subtype of String

### ISSUE THREAD

**Issue by iLl3ctRo** [kawal7415/excel#1]
When I try to encode an Excel object back to an file I always get this error. Even when i try to run the provided example. Everything else is just working fine for me.

**Comment by kawal7415** [comment]
You are trying to run from pub.dev/packages/excel or directly from the github ?

**Comment by iLl3ctRo** [comment]
I have copied the example directly in one of my flutter projects and also tried it as an command line tool writtewn with dart

**Comment by kawal7415** [comment]
Can you show me the error log ?

**Comment by kawal7415** [comment]
As you have not replied for long, 
I thinks the issue might be resolved on your side
I am closing this issue.
If you have any issue don't hesitate to open up the issue.

~Thank You
**LONG LIVE OPEN S🔥URCE**
