### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by piecubed** [kawal7415/excel#10]
Are you planning on adding various cell styling / text styling?

**Comment by kawal7415** [comment]
Yes in the future updates we are working on to provide font-family, font-size, italic, bold, underline and various other styling options.

**Comment by piecubed** [comment]
@kawal7415 When do you think that will be available?  And planning on adding charts?

**Comment by kawal7415** [comment]
Charts not for now but surely in near future.

You will get some new functionality related to styling and more by tomorrow on https://pub.dev/packages/excel

Thank You
Stay Tuned...
Long Live Open S🔥urce

**Comment by piecubed** [comment]
Great!  Can you add formulas too? ~~Sorry for all the requests, its what you get if you are the only decent library for something in a language!~~

**Comment by kawal7415** [comment]
Yes, we had already started to work on Formulas.

**Comment by piecubed** [comment]
Great!

**Comment by apps-auth** [comment]
Hello, first I would like to thank you for the beautiful package.

Is there any provision for introducing:
-Font Family
-Text Size
-Italic
-Underline
-Bold

Is there any way we can help you? This would be an extremely useful feature

**Comment by kawal7415** [comment]
Yes, we will be providing that.

We had started working with very different approach in order to provide the features and functionality more fastly and smoothly.

You can check branch : beta (unstable)

**Comment by kawal7415** [comment]
Excel: ^1.0.9 is out https://pub.dev/packages/excel
Now excel being **`more faster`** than before.

Added Functionalities:
**Cell Type
Copy Sheet
Rename Sheet
Delete Sheet
Link Sheets
Un-Link Sheets
Font Family (182 Font Family Available)
Font Size
Italic
Underline
Bold**

Thank You
Long Live Open S🔥urce
