### ISSUE TITLE
Because every version of flutter_test from sdk depends on xml 3.5.0 and excel >=1.0.4 depends on xml ^4.1.0

### ISSUE THREAD

**Issue by rogue414G** [kawal7415/excel#11]
I have tried to use excel 1.0.4
I can't advance by this error..
Please, help me. Thank you.
"Because every version of flutter_test from sdk depends on xml 3.5.0 and excel >=1.0.4 depends on xml ^4.1.0, flutter_test from sdk is incompatible with excel >=1.0.4.

So, because flutter_app_sheet depends on both excel ^1.0.4 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because flutter_app_sheet depends on both excel ^1.0.4 and flutter_test any from sdk, version solving failed.)"

**Comment by kawal7415** [comment]
Can You share your pubspec.yaml file ?

**Comment by kawal7415** [comment]
If it not works then please run flutter doctor -v and post your logcat here.


Thank You

**Comment by kawal7415** [comment]
Hey I found that issue is being resopved after running command
flutter update-packages --force-upgrade

**Comment by rogue414G** [comment]
Thank you.
I will try to it and let you know again..
Thank you again.

**Comment by kawal7415** [comment]
Closing this issue as command `flutter update-packages --force-upgrade` worked and  version solving failed no longer appeared.
Feel free to further re-open up the issue if you feel so.

~Thank You
LONG LIVE OPEN S🔥URCE

**Comment by rogue414G** [comment]
Thank you .
I will try to and let you know about result .
Thank you again

**Comment by kawal7415** [comment]
> Closing this issue as command `flutter update-packages --force-upgrade` worked and version solving failed no longer appeared.
> Feel free to further re-open up the issue if you feel so.
> 
> ~Thank You
> LONG LIVE OPEN S🔥URCE

I had tried it by myself.
