### ISSUE TITLE
Support updating data by index of biggest col-row which have data

### ISSUE THREAD

**Issue by sil-main-coo** [kawal7415/excel#13]
I have problem that I want to update data of a file which was existed. I want add this data **to column or row has data which in last of sheet**.
But i can't determine where index of that is. 
Please show me any ways ?

P/S: This package is awesome !

**Comment by justraman** [comment]
Do you want to update those sheet data or want to append additional data to the rows?

**Comment by kawal7415** [comment]
Are you asking for Find and Replace functionality ?

**Comment by sil-main-coo** [comment]
Thanks for the quick reply. 
Just as @justraman said. And Find and Replace functionality, that's great. 
Is it being supported ?

**Comment by kawal7415** [comment]
We are working on the Find and Replace functionality and will provide this functionality in the coming week.
