### ISSUE TITLE
Affecting formulas after editing

### ISSUE THREAD

**Issue by ialameh** [kawal7415/excel#16]
Hi,
I have a base excel sheet with formulas in it, after I edited the sheet and saved it, the formulas were corrupted. 
Are you aware about that

Thank you so much for such a great package
Sam,

**Comment by kawal7415** [comment]
Yes we are aware about it.
And we had already started to work on giving the Formula functionality so that the excel will not corrupt.

Thank You for telling us where we are lacking.
We will try to fix this soon by the coming week.

Stay Tuned.
LONG LIVE OPEN SURCE

**Comment by ialameh** [comment]
your work on this is awesome, 

thank you so much
