### ISSUE TITLE
NoSuchMethodError: The method 'removeWhere' was called on null

### ISSUE THREAD

**Issue by ialameh** [kawal7415/excel#20]
Hi,
I am having an error on removing a row, is this a known issue?

Sam

**Comment by ialameh** [comment]
`await loadExcel(sheet: sheet, fileName: '$dir/sofplist.xlsx')
        .then((onValue) => onValue.removeRow(sheet, index))
        .then((onValue) =>
            saveExcelSheet(excel: onValue, fileName: 'nsofplist.xlsx'));`

**Comment by ialameh** [comment]
`
await loadExcel(sheet: sheet, fileName: '$dir/sofplist.xlsx')
        .then((onValue) => onValue.removeRow(sheet, index))
        .then((onValue) =>
            saveExcelSheet(excel: onValue, fileName: 'nsofplist.xlsx'));
`

**Comment by ialameh** [comment]
> await loadExcel(sheet: sheet, fileName: '$dir/sofplist.xlsx')
        .then((onValue) => onValue.removeRow(sheet, index))
        .then((onValue) =>
            saveExcelSheet(excel: onValue, fileName: 'nsofplist.xlsx'));

**Comment by kawal7415** [comment]
We celebrate every single issue.

Thanks for telling us ♥️.

Found out the bug and corrected.

Update will be pushed to pub in a short while.

**Comment by kawal7415** [comment]
**excel: 1.0.6** is live : https://pub.dev/packages/excel

Sorry for the inconvenience caused before.

Stay Tuned.
LONG LIVE OPEN S🔥URCE

**Comment by ialameh** [comment]
expect another donation soon :D

**Comment by ialameh** [comment]
[sofplist.xlsx](https://github.com/kawal7415/excel/files/4661969/sofplist.xlsx)
Following a sample file, please can you try to delete rows from it and check it out.
if it work can you post the method (along with the saving of the file)

The file exist in the application storage no in the assets

**Comment by kawal7415** [comment]
I wonder why this is happening !

Going through it. Will try best to get it resolved by tonight.

**Comment by kawal7415** [comment]
Now it's working fine.
I hope it will work for you too !!

Feel free to reopen or open up the issue without any hesitation if you finds out any other trouble.

Thanks Again.
Stay Tuned.
LONG LIVE OPEN S🔥URCE
