### ISSUE TITLE
Doubt about font customization

### ISSUE THREAD

**Issue by apps-auth** [kawal7415/excel#23]
Hello, first I would like to thank you for the beautiful package.

Is there any provision for introducing:
-Font Family
-Text Size
-Italic
-Underline
-Bold

Is there any way we can help you? This would be an extremely useful feature

**Comment by kawal7415** [comment]
Yes, we will be providing that.

We had started working with very different approach in order to provide the features and functionality more fastly and smoothly.

You can check branch : beta **(unstable)**

**Comment by kawal7415** [comment]
Excel: ^1.0.9 is out https://pub.dev/packages/excel
Now excel being **`more faster`** than before.

Added Functionalities:
**Copy
Rename
Delete
Link Sheets
Un-Link Sheets
Font Family (182 Font Family Available)
Font Size
Italic
Underline
Bold**
