### ISSUE TITLE
Not compatible with flutter_test

### ISSUE THREAD

**Issue by akaenner** [kawal7415/excel#25]
If I include excel in my project I get the following dependency error:

[MyApp] flutter pub get
Running "flutter pub get" in MyApp...                  
Because every version of flutter_test from sdk depends on xml 3.6.1 and excel >=1.0.4 depends on xml ^4.1.0, flutter_test from sdk is incompatible with excel >=1.0.4.
So, because Herein depends on both excel ^1.0.8 and flutter_test any from sdk, version solving failed.

pub get failed (1; So, because MyApp depends on both excel ^1.0.8 and flutter_test any from sdk, version solving failed.)
exit code 1
------------

What should I do? I need both: tests and excel.

**Comment by kawal7415** [comment]
Use command : `flutter update-packages --force-upgrade`

Tell me if this works for you !

~Thank You
LONG LIVE OPEN S🔥URCE

**Comment by akaenner** [comment]
Now I get a slightly different dependency error. Basically the same but the required version for flutter_test is now 3.7.0:

Because every version of flutter_test from sdk depends on xml 3.7.0 and excel >=1.0.4 depends on xml ^4.1.0, flutter_test from sdk is incompatible with excel >=1.0.4.

Here is my flutter doctor output: 

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by kawal7415** [comment]
### Solved
Try below steps:

1) Open project folder and remove **excel** dependency
2) Add these lines in your project's pubspec.yaml
```
dependency_overrides:
  xml: ^4.1.0
```
after adding it will look like:
```
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  xml: ^4.1.0
```
3) run `flutter clean` in the project folder.
4) Close project folder
5) Open terminal and run below commands :
      > `flutter upgrade`

      > `pub cache repair`

      > `flutter update-packages --force-upgrade`

6) Open project folder and add the dependency `excel: ^1.0.8`

**Comment by akaenner** [comment]
Thank you very much. This works :-)

**Comment by kawal7415** [comment]
Happy to help.
Stay Tuned...

More functionality is coming within next week with excel being more **_`faster`_** than now.
