### ISSUE TITLE
Because every version of flutter_test from sdk depends on xml 3.7.0 and excel >=1.0.4 depends on xml ^4.1.0, flutter_test from sdk is incompatible with excel >=1.0.4. So, because exceltest depends on both excel ^1.0.9 and flutter_test any from sdk, version solving failed. pub get failed (1; So, because exceltest depends on both excel ^1.0.9 and flutter_test any from sdk, version solving failed.)

### ISSUE THREAD

**Issue by cicelcup** [kawal7415/excel#26]
Hello. I did what you said in the issues #11 (flutter update-packages --force-upgrade) but I still have the same issue. I cannot use excel 1.09 (I can only use excel 1.03)
my flutter -doctor

/home/jorge/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, v1.17.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.0 at /home/jorge/flutter
    • Framework revision e6b34c2b5c (6 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/jorge/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/90/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/88/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/90/android-studio
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Comment by cicelcup** [comment]
I solved using 
dependency_overrides:
  xml: '4.2.0'

according the suggestion in:
https://flutter.dev/docs/development/packages-and-plugins/using-packages

**Comment by pratikbutani** [comment]
Have you checked [this article](https://pratikbutani.medium.com/flutter-2-upgrade-flutter-version-solving-failed-error-33ac1087cb6b)
