### ISSUE TITLE
Reading a cell with sheet.cell() changes the data to null

### ISSUE THREAD

**Issue by zakton5** [kawal7415/excel#28]
Pretty strange issue here. This is my code. I'm essentially parsing a table

[Test Upload.xlsx](https://github.com/kawal7415/excel/files/4781279/Test.Upload.xlsx)

```dart
final bytes = File(filePath).readAsBytesSync();
final excel = Excel.decodeBytes(bytes);
final defaultSheet = await excel.getDefaultSheet();
final sheet = excel[defaultSheet];
// Cell B1 is 60 here
final widthCell = sheet.cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: 0));
// But now it is null
print(widthCell.value);
```
There is code in `cell()` on line 104 and 105 of `sheet.dart` that seems to be causing this. It seems that is just isn't carrying the value over. Am I doing something wrong?

**Comment by zaytri** [comment]
I've also experienced this, had to workaround by not using `cell()`.
```dart
defaultSheet.row(0)[1].value
```

**Comment by kawal7415** [comment]
Thanks @zakton5 for letting us know about this.

It's fixed now and will be updated in the new version by tomorrow: `excel: ^1.1.0`
