### ISSUE TITLE
[Question] Empty sheet on Excel creation

### ISSUE THREAD

**Issue by ja2375** [kawal7415/excel#3]
Hi,
First of all, thank you very much for this awesome library! It does work perfectly well despite it's not complete yet.

I have some kind of an issue, we could say. Because it's not a bug, just some behaviour i wasn't expecting.

The "issue" is that i create an XLSX just fine, with a custom named sheet. The content gets added just fine by calling the `updateCell()` method. Everything seems to be fine, until i export it to a file. That file contains the sheet i created, with my custom name. But it also contains another sheet. That sheet is called "Sheet1", and it's the default sheet that displays to the user and also it is empty.

My question is: How can i get rid of that empty sheet "Sheet1"?

Many thanks again!

**Comment by kawal7415** [comment]
Yes! you are right. I saw this behaviour now.

Not to worry in the coming update with **facility to merge columns and rows**, I will fix this unexpected behaviour.


Thank You.

**Comment by ja2375** [comment]
OK, many thanks!!!

Looking forward for that update :P

**Comment by kawal7415** [comment]
Your request has been processed and we will be providing a method so that you will be able to set the sheet as opening default.
It will be published on https://pub.dev/packages/excel .

Thank You
Stay Tuned...
