### ISSUE TITLE
Unable to delete or rename Sheet

### ISSUE THREAD

**Issue by VigneshRM93** [kawal7415/excel#31]
Unhandled Exception: RangeError (index): Index out of range: no indices are valid: 3

**Comment by kawal7415** [comment]
Can you show the snippet of code which you are using to delete the sheet?

**Comment by VigneshRM93** [comment]
reportExcel.delete('Sheet1');

**Comment by kawal7415** [comment]
Please provide your Stack-Trace, So that we can find out what have caused this error.

**Comment by VigneshRM93** [comment]
`E/flutter (27275): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Index out of range: no indices are valid: 3
E/flutter (27275): #0      RangeError.checkValidIndex (dart:core/errors.dart:330:7)
E/flutter (27275): #1      XmlNodeList.removeAt (package:xml/src/xml/utils/node_list.dart:177:16)
E/flutter (27275): #2      Excel.delete.<anonymous closure> (package:excel/src/excel.dart:298:17)
E/flutter (27275): #3      List.forEach (dart:core-patch/growable_array.dart:282:8)
E/flutter (27275): #4      Excel.delete (package:excel/src/excel.dart:282:9)
E/flutter (27275): #5      _MonthlyReportState.generateReport (package:financeadmin/pages/fragments/MonthlyReport.dart:559:26)
E/flutter (27275): <asynchronous suspension>
E/flutter (27275): #6      _MonthlyReportState.getReport.<anonymous closure>.<anonymous closure> (package:financeadmin/pages/fragments/MonthlyReport.dart:277:9)
E/flutter (27275): #7      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
E/flutter (27275): #8      _MonthlyReportState.getReport.<anonymous closure> (package:financeadmin/pages/fragments/MonthlyReport.dart:270:7)
E/flutter (27275): #9      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (27275): #10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (27275): #11     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (27275): #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (27275): #13     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (27275): #14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (27275): #15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
E/flutter (27275): #16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
E/flutter (27275): #17     ApiProvider.generateCollInfo (package:financeadmin/network/ApiProvider.dart)
E/flutter (27275): <asynchronous suspension>
E/flutter (27275): #18     _MonthlyReportState.getReport (package:financeadmin/pages/fragments/MonthlyReport.dart:267:10)
E/flutter (27275): #19     _MonthlyReportState.build.<anonymous closure> (package:financeadmin/pages/fragments/MonthlyReport.dart:253:31)
E/flutter (27275): #20     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (27275): #21     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (27275): #22     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (27275): #23     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (27275): #24     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (27275): #25     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (27275): #26     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (27275): #27     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (27275): #28     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (27275): #29     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (27275): #30     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (27275): #31     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (27275): #32     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (27275): #33     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (27275): #34     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (27275): #35     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (27275): #36     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (27275): #37     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (27275): #38     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (27275): #39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (27275): #40     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (27275): #41     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
`

**Comment by kawal7415** [comment]
I had tracked down the bug and had started working on it, expect a fix in a day or two
