### ISSUE TITLE
Cannot update to versions past 1.0.3

### ISSUE THREAD

**Issue by krumpli84** [kawal7415/excel#33]
Getting version 1.0.9 gives me this error:
```
Because every version of flutter_test from sdk depends on xml 3.6.1 and excel >=1.0.4 depends on xml ^4.1.0, flutter_test from sdk is incompatible with excel >=1.0.4.
So, because application depends on both excel ^1.0.9 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because application depends on both excel ^1.0.9 and flutter_test any from sdk, version solving failed.)
```

**Comment by kawal7415** [comment]
Similar issues have been solved in the past : https://github.com/kawal7415/excel/issues/26 , https://github.com/kawal7415/excel/issues/11

If it still doesn't helps, Feel happy to reopen the issue again.

**Comment by krumpli84** [comment]
Yeah those solutions did nothing for me unfortunately. Same issue persists.

**Comment by VigneshRM93** [comment]
I had the same issue. Solved using [this](https://github.com/kawal7415/excel/issues/25#issuecomment-636297104)

**Comment by kawal7415** [comment]
@krumpli84 Try the above solution and let us know if that works for you. !

**Comment by kawal7415** [comment]
I hope that the above solution by @VigneshRM93 helped you out.

If you find any issue, then open up issue again.

Thanks.
