### ISSUE TITLE
Error in excel when open the file

### ISSUE THREAD

**Issue by cicelcup** [kawal7415/excel#38]
Hello. I am creating an excel file using your library as follow:

    var excel = Excel.createExcel();
    var sheet = excel[AppStrings.excelSheetName];
    excel.setDefaultSheet(AppStrings.excelSheetName);

    CellStyle cellStyle = CellStyle(
        backgroundColorHex: "#F44336",
        fontColorHex: "#FFFFFF",
        bold: true,
        verticalAlign: VerticalAlign.Top);

    //Create the title of the fields for each column
    for (int index = 0; index < _questionsName.length; index++) {
      var cell = sheet
          .cell(CellIndex.indexByColumnRow(rowIndex: 0, columnIndex: index));
      cell.cellStyle = cellStyle;
      cell.value = _questionsName[index];
    }

    //Write the excel file
    String outputFile = "$path/$file";
    excel.encode().then((onValue) {
      File(join(outputFile))
        ..createSync(recursive: true)
        ..writeAsBytesSync(onValue);
    });

Everything works well... Later on I create a routine to send it by email and I successfully open the file. But the issue comes when I download the file directly from the email, tried to copy one of the sheet to another excel file... it seems excel not recognize the file and crash immediately. 

I find a work around that is dowloading the file, saving as with another name and then copy the sheet to another file excel. But this is not what I would like to do. I would like to be able to copy the excel sheet directly from the original file generated.

**Comment by ialameh** [comment]
what you are explaining here sound like there is an issue in the mime type within the email, and nothing to do with package itself. did you setup the mime type as 

`application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
`
in the email?

**Comment by cicelcup** [comment]
Hello. Thanks for answer me... the email opens well and the file opens and downloads wells. the issue is when I tried to copy a sheet from the file to another excel file before I save it. 
I tried several times checking with part of the code is producing the error. I found it here: 

var sheet = excel[AppStrings.excelSheetName];
excel.setDefaultSheet(AppStrings.excelSheetName);
when I create a sheet using this procedure, any time that I tried to copy the sheet to another excel file, excel crashed. (this doesn't happen if I saved the file into excel). 

Now I am getting the default sheet page and I successfully can copy that sheet to another excel file like this: 

    var excel = Excel.createExcel();
    //get the sheet Name (other sheet creation throws error so far)
    var sheetName = await excel.getDefaultSheet();
    //Create the sheet
    var sheet = excel[sheetName];

In this way, it works perfectly... So, I guess the errors come when we create a excel sheet or when we set the default excel page

I'm trying to understand the package to see what happens, but I am not so familiar with it.

**Comment by kawal7415** [comment]
Are you trying to copy one sheet from excel to another excel files,
like communicating data between 2 excel files ??

**Comment by cicelcup** [comment]
No.. I am just would like to write data in another sheet different than the default one... it's like create a new sheet, set some data and save it

**Comment by kawal7415** [comment]
Can you post the log of the issue ??

**Comment by cicelcup** [comment]
I cannot reproduce any log. In flutter everything appears to be ok. The issue comes when I opened the generated excel file and try to copy that sheet to another workbook in another excel file (it seems the excel is not recognizable).

The errors come when I create the excel in this way:
var excel = Excel.createExcel();
var sheet = excel[AppStrings.excelSheetName];
excel.setDefaultSheet(AppStrings.excelSheetName);

instead of:
var excel = Excel.createExcel();
//get the sheet Name (other sheet creation throws error so far)
var sheetName = await excel.getDefaultSheet();
//Create the sheet
var sheet = excel[sheetName];

**Comment by kawal7415** [comment]
Ok can you post the issue text from the terminal or log cat related to excel so that we can know what problem you are facing.

**Comment by kawal7415** [comment]
I hope the issue will be resolved by now on your own,

If you thinks that the issue still persist then feel free to re-open the issue.
