### ISSUE TITLE
General column input number would cause error

### ISSUE THREAD

**Issue by ScottHuangZL** [kawal7415/excel#4]
Attached please find the sample excel, if you put number in general type column would show below error, if you change the input number to any text, the error gone.

[sample.xlsx](https://github.com/kawal7415/excel/files/4515770/sample.xlsx)

**type '_Smi' is not a subtype of type 'String'**
#0      Excel._createCell (package:excel/src/excel.dart:885)
#1      Excel._replaceCell (package:excel/src/excel.dart:874)
#2      Excel._updateCell (package:excel/src/excel.dart:839)
#3      Excel._updateSheetElements.<anonymous closure> (package:excel/src/excel.dart:415)
#4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379)
#5      Excel._updateSheetElements (package:excel/src/excel.dart:408)
#6      Excel.encode (package:excel/src/excel.dart:570)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45)
#8      Excel.encode (package:excel/src/excel.dart:559)

**Comment by ashumendra77** [comment]
Thanks,

I'll look into it and fix this by the end of this month.

**Comment by kawal7415** [comment]
Hey It will be helpful if you can provide a sample code to reproduce that error, It will help to go much deeper.


Thank You

**Comment by kawal7415** [comment]
We had solved you issue,

A new version will be published by the end of week with more enhanced features and faster processing of excel and also with your issue resolved.

Than You Stay Tuned
