### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by x2ecom** [kawal7415/excel#42]
I have a data set of approximately 6000 records by 20 columns. When executing the code below, the sheet.appendRow(row) seems to take extremely long. If I remove the append it executes in less than a second, if I add it back in it takes 2+ minutes to complete. Am I missing a step or is there an easier (faster) means of importing an entire set of data into excel?

Example (sheet is the default) :

        List<String> row = List<String>();
        i++;
        print(i.toString());
        columns.forEach((column)
        {
          if (map.containsKey(column))
                row.add(map[column].toString());
          else row.add('');
        });
        sheet.appendRow(row);

**Comment by kawal7415** [comment]
I had applied the fix and now it seems to work faster than before.

You can upgrade to version:
````yaml
excel: ^1.1.3

**Comment by x2ecom** [comment]
Seems to have improved the performance except now I just get empty spaces??? If I compile under the old it works, with the new version the file if blank with a few exceptions.

**Comment by kawal7415** [comment]
I have applied the fix, It seems to work now.

You can upgrade to latest version:
````yaml
excel: ^1.1.4
````
I tested out:

```dart
  List<List<String>> list = List.generate(
      6000, (index) => List.generate(20, (index1) => '$index $index1'));

  print(" appending of rows started ");

  Stopwatch stopwatch = new Stopwatch()..start();
  list.forEach((row) {
    sheet.appendRow(row);
  });

  print('appending of rows completed in ${stopwatch.elapsed}');
```

**Comment by x2ecom** [comment]
works great. thanks and cheers
