### ISSUE TITLE
excel["filename"] not working in stable channel

### ISSUE THREAD

**Issue by kechankrisna** [kawal7415/excel#43]
Sheet sheet = excel['$filename']; doesn't work in flutter stable channel

Because every version of flutter_test from sdk depends on xml 3.6.1 and excel >=1.0.4 depends on xml ^4.1.0, flutter_test from sdk is incompatible with excel >=1.0.4.

**Comment by kawal7415** [comment]
Similar issues have been solved in the past,

You can see in the documentation section : https://github.com/kawal7415/excel#frequent-issues

or look at issue: https://github.com/kawal7415/excel/issues/25

**Comment by kawal7415** [comment]
As it's been a long time, I hope that the issue has been resolved by now.
