### ISSUE TITLE
Black screen while _workbook = await Excel.decodeBytes(_fileContentInBytes);

### ISSUE THREAD

**Issue by wpepen** [kawal7415/excel#44]
Hi! I would like your support on this. 

The package works fine, however is see a 'black screen' while executing the following code:

Excel  _workbook = await Excel.decodeBytes(_fileContentInBytes);

It remains about 3 or 4 seconds while processing the file content, and I believe it is because of the file size.

Is there any possibility to show a 'pop up' and say processing, or present something different than the black screen? 

Thanks in advance

**Comment by kawal7415** [comment]
Thanks for letting me know about this.

But As I can see that it will be easy for you to do that by your own on the **flutter side** with the combinational use of async, await and progress dialog and then as soon as the async call from the [Excel](https://github.com/kawal7415/excel) library returns then hide the dialog and do your stuff.

As [Excel](https://github.com/kawal7415/excel) only helps you in providing api to interact with the excel files with the use of dart core codes,

we don't depend on flutter for anything. **So, showing a message or anything that includes rendering is not possible.**

Closing the issue as this seems to be resolved or **it should be asked on stack-overflow for doubts regarding flutter**.

If you find out any bug or problem in using [Excel](https://github.com/kawal7415/excel) then do let us know about it.
