### ISSUE TITLE
Create Multiple Sheets

### ISSUE THREAD

**Issue by cenezoic123** [kawal7415/excel#6]
Is it possible to create a multiple sheets, example MySheet1, MySheet2, MySheet3. . . . ?

**Comment by rma6** [comment]
Yes, it's possible. The first argument of `updateCell()` takes a String as input for the sheet name.
So, if you do something like

```
var decoder = Excel.createExcel();

decoder.updateCell("Sheet1", CellIndex.indexByString("A1"), "val");
decoder.updateCell("Sheet2", CellIndex.indexByString("A1"), "val");
```

you'll have a document with two sheets: Sheet1 and Sheet2.

**Comment by kawal7415** [comment]
Yes its possible to create, whenever u call decoder.updateCell() with the desired sheetName

then if the sheet doesn't exist then it will be automatically created or if it exists then it will be updated in the desired cell

**Comment by wuuzw** [comment]
seems like it won't create a new sheet if you use appendRow()

**Comment by kawal7415** [comment]
Its working now.

Long Live Open S🔥 urce
