### ISSUE TITLE
Add support for cell type

### ISSUE THREAD

**Issue by bakua** [kawal7415/excel#7]
Hello, 

it would be helpfult if there is a possibility to set a column type. At least to distinguish between text and number cells. This way, it would be easy to perfom math operations with the file afterwards.

Thank you

**Comment by justraman** [comment]
Internal structure of XLS/XLSX files does not include any row/column type.
However you can distinguish b/w number and text by parsing it.
````dart
 getCellType(cell){
  try{
    double.parse(cell);
    return 'number';
  }
  catch(e){
    return 'text';
  }
}
````

**Comment by kawal7415** [comment]
In the future updates I will give support for the cell Type

Stay Tuned..
